spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/projectdb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB
application:
  security:
    jwt:
      expiration: 86400000 # 86400000 # a day
      secret-key: JBAPhjnzukkT3WlEWa2V7itahxD3QE+KnZc3azNdrrQnyGolUKhQVZYgO5vkxo2/tDuK2hDHLFiTH6qF2FQmIg==
      refresh-token:
        expiration: 604800000 # 7 days